name: Exiled.Installer CI

on: [push, pull_request]

jobs:
  build:
    name: .Net Core ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          target: linux-x64
          program_name: Exiled.Installer-Linux
        - os: windows-latest
          target: win-x64
          program_name: Exiled.Installer-Win.exe
    timeout-minutes: 30

    steps:
    - uses: actions/setup-dotnet@v1.5.0

    - uses: actions/checkout@v2.3.1

    - name: Install dependencies for ${{ matrix.target }}
      run: dotnet restore Exiled.Installer -r ${{ matrix.target }}

    - name: Build ${{ matrix.target }}
      run: dotnet publish Exiled.Installer -r ${{ matrix.target }} -c release -o builds/${{ matrix.target }}

    - name: Resolve permissions
      if: matrix.os == 'ubuntu-latest'
      run: chmod +x builds/${{ matrix.target }}/${{ matrix.program_name }}

    - name: Upload ${{ matrix.target }} build
      uses: actions/upload-artifact@v2
      with:
        name: Exiled.Installer-${{ matrix.target }}
        path: builds/${{ matrix.target }}
