# This is a basic workflow to help you get started with Actions

name: EXILED CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore Packages
      run: nuget restore EXILED.sln
    
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    
    - name: Download references
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/build_deps/References.zip'
        file-name: 'References.zip'
        location: $GITHUB_WORKSPACE
    
    - name: Download 7zip
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.7-zip.org/a/7z1900-extra.7z'
        file-name: '7zip.exe'
        location: $GITHUB_WORKSPACE
    
    - name: Extract Refs
      run: ./7zip.exe References.zip -oReferences -r -y
      
      
    - name: Build
      env: 
        EXILED_REFERENCES: $GITHUB_WORKSPACE\\References
      run: msbuild $GITHUB_WORKSPACE\\EXILED.sln -p:Configuration=release
      
