name: Release

on:
  push:
    tags:
      - '*.*.*'

defaults:
  run:
    working-directory: ./EXILED

env:
  EXILED_REFERENCES_URL: https://misaka-zerotwo.github.io/SL-References/Dev.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/EXILED/References
  EXILED_DLL_ARCHIVER_URL: https://github.com/Exiled-Official/EXILED-DLL-Archiver/releases/latest/download/EXILED-DLL-Archiver.exe

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
  
      - name: Setup Nuget
        uses: iRebbok/setup-nuget@master
  
      - uses: actions/checkout@v2.3.4
  
      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/EXILED/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}
  
      - name: Build
        env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
        shell: pwsh
        run: |
          ./build.ps1 -BuildNuGet
          $File = (Get-ChildItem -Path . -Include 'EXILEDOFFICIAL.*.nupkg' -Recurse).Name
          Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append
  
      - name: Upload nuget package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PackageFile }}
          path: EXILED/${{ env.PackageFile }}
          
      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_DLL_ARCHIVER_URL }} -OutFile ${{ github.workspace }}/EXILED/EXILED-DLL-Archiver.exe
    
      - name: Packaging results as tar.gz
        shell: pwsh
        run: ./packaging.ps1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: EXILED/bin/Release/Exiled.tar.gz
